services:
  redis:
    image: "redis:7"
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  db:
    image: postgres:17
    restart: always
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}

  django-web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - ~/.ssh:/home/appuser/.ssh:ro
    env_file:
      - .env

  celery:
    build: .
    restart: always
    command: celery -A educational worker -l info
    depends_on:
      - django-web
      - redis
    env_file:
      - .env

  nginx:
    image: nginx:1.29
    ports:
      - "8001:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - static_volume:/app/staticfiles
    depends_on:
      - django-web

volumes:
  redis_data:
  postgres_data:
  static_volume: