# Generated by Django 5.2.2 on 2025-09-12 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="birth_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
